# Generated by Django 4.2.17 on 2024-12-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=200, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=9, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=9, unique=True, verbose_name='RG')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Estado')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da compra')),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.clientes', verbose_name='Cliente')),
                ('pulseira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.pulseira', verbose_name='Pulseira')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_commerce.estado', verbose_name='Estado'),
        ),
    ]
