# Generated by Django 4.2.17 on 2024-12-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_clientes_estado_compra_clientes_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='Cliente',
        ),
    ]
