# Generated by Django 4.2.17 on 2024-12-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_rename_clientes_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulseira',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pulseiras/', verbose_name='Imagem'),
        ),
    ]
