# Generated by Django 4.2.17 on 2024-12-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_pulseira_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
