# Generated by Django 4.2.17 on 2024-12-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_compra_valor_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='clientes',
            new_name='cliente',
        ),
    ]
